monitoring:
  interval: 1800             # seconds to sleep between runs, use 0 for single run/cron mode
  alert_snooze: 3            # number of intervals to sleep before ressending alert 
                             # 1800/3 will check planets every 30min, and will snooze 90min after an alert
# alerting using textbelt
text_alerting:
  endpoint: https://textbelt.com/text             # this shouldn't change just get an API key: https://textbelt.com/
  phone_number: 5555555555
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  alert_text: "ALERT:Check the following planets: "

# Alert to an urbit group on a "reporter" ship.
urbit_group_alert:
  reporter_ship_name: ~watsup-watsup-watsup-watsup
  reporter_ship_address: https://moon.watsup.net:443
  reporter_ship_code: watsup-watsup-watsup-watsup
  # group to post alert - obtain group name (mychat-1313) via URL, e.g. .../chat/ship/~tictuc-lacdef-sitsev-lomrem/mychat-1313
  reporter_group_name: mychat-1313
  reporter_alert_text: "ALERT:Check the following planets: "

# planet/star/galaxy endpoints to monitor
endpoints:
  zod: 
    address: http://127.0.0.1:8080/
    code: lidlut-lidlut-lidlut-lidlut
  walbex-hasper-pollyt-hocnyx--macben-padper-lagdeb-marzod: 
    address: https://my.watsup.net/
    code: watsup-watsup-watsup-watsup
  watsup-watsup: 
    address: yyyyy.net
    code: ponbes-ponbes-ponbes-ponbes
